# /etc/nginx/conf.d/dsh.conf
#
# dsh-docker:
#   ACCESS_MODE=local
#   BIND_ADDRESS=127.0.0.1
#   DSH_PORT=3080

server {
    listen 80;
    server_name dsh.example.com;

    location / {
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_buffering off;
        proxy_pass http://127.0.0.1:3080;
    }
}
